#!/bin/bash
echo "🚀 ShadowCheck Production Status"
echo "================================="
echo ""
echo "📦 Containers:"
docker ps --filter name=shadowcheck --format "  {{.Names}} - {{.Status}}"
echo ""
echo "🌐 Services:"
echo "  Frontend:  http://localhost:5173"
echo "  Backend:   http://localhost:5000"
echo "  pgAdmin:   http://localhost:8080"
echo "  Postgres:  localhost:5432"
echo ""
echo "🔧 Quick Commands:"
echo "  Start:   ./start-prod-clean.sh"
echo "  Stop:    docker-compose -f docker-compose.prod.yml stop"
echo "  Logs:    docker logs shadowcheck_backend"
echo ""
