#!/usr/bin/env bash
# Import WiGLE SQLite export into PostgreSQL
# Based on sqlite_to_postgres_import.sh

set -euo pipefail

SQLITE_FILE="${1:-}"
PG_DB="${2:-sigint}"
DEVICE_SCHEMA="${3:-}"

if [[ -z "${SQLITE_FILE}" || ! -f "${SQLITE_FILE}" ]]; then
  echo "Usage: $0 <sqlite_file> [pg_database] [schema_name]"
  echo "Example: $0 wigle_export.sqlite sigint device1"
  exit 1
fi

# Infer schema name from filename if not provided
if [[ -z "$DEVICE_SCHEMA" ]]; then
  DEVICE_SCHEMA="$(basename "$SQLITE_FILE" | sed 's/\.[^.]*$//' | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_]/_/g')"
fi

LOGFILE="import_${DEVICE_SCHEMA}_$(date +%Y%m%d_%H%M%S).log"

echo "[*] Import plan:"
echo "    SQLite file: ${SQLITE_FILE}"
echo "    Database:    ${PG_DB}"
echo "    Schema:      ${DEVICE_SCHEMA}"
echo "    Log file:    ${LOGFILE}"

# Create schema
echo "[*] Creating schema: ${DEVICE_SCHEMA}"
psql -d "$PG_DB" -qAt -c "DROP SCHEMA IF EXISTS ${DEVICE_SCHEMA} CASCADE;"
psql -d "$PG_DB" -qAt -c "CREATE SCHEMA ${DEVICE_SCHEMA};"

# Phase 1: Import with minimal changes
echo "[*] Converting SQLite schema to PostgreSQL"
SCHEMA_SQL="schemas/pg_schema_${DEVICE_SCHEMA}_phase1.sql"

sqlite3 "$SQLITE_FILE" .schema | sed -E "
  s/\r$//;
  /^PRAGMA /d; /^BEGIN TRANSACTION;/d; /^COMMIT;/d;
  /sqlite_sequence/Id;
  
  # Retarget tables to device schema
  s/CREATE TABLE[[:space:]]+(\"?)([A-Za-z0-9_]+)\1/CREATE TABLE ${DEVICE_SCHEMA}.\\1\\2\\1/gI;
  s/CREATE INDEX[[:space:]]+(\"?)([A-Za-z0-9_]+)\1/CREATE INDEX IF NOT EXISTS \\1\\2\\1/gI;
  s/([[:space:]]+)ON[[:space:]]+(\"?)([A-Za-z0-9_]+)\2/\\1ON ${DEVICE_SCHEMA}.\\2\\3\\2/gI;
" > "$SCHEMA_SQL"

# Try Phase 1 import
echo "[*] Applying schema (Phase 1)"
if ! psql -v ON_ERROR_STOP=1 -d "$PG_DB" -f "$SCHEMA_SQL" 2>&1 | tee -a "$LOGFILE"; then
  echo "[!] Phase 1 failed, trying Phase 2 with compatibility fixes"
  
  # Phase 2: Add type compatibility fixes
  SCHEMA_SQL_PHASE2="schemas/pg_schema_${DEVICE_SCHEMA}_phase2.sql"
  sqlite3 "$SQLITE_FILE" .schema | sed -E "
    s/\r$//;
    /^PRAGMA /d; /^BEGIN TRANSACTION;/d; /^COMMIT;/d;
    /sqlite_sequence/Id;
    
    # Type fixes for PostgreSQL compatibility
    s/INTEGER[[:space:]]+PRIMARY[[:space:]]+KEY[[:space:]]+AUTOINCREMENT/BIGINT GENERATED BY DEFAULT AS IDENTITY/Ig;
    s/\bLONG\b/BIGINT/g;
    s/\bBLOB\b/BYTEA/Ig;
    s/\bDOUBLE\b/DOUBLE PRECISION/Ig;
    s/\bFLOAT\b/DOUBLE PRECISION/Ig;
    
    # Retarget to schema and add safety
    s/CREATE TABLE[[:space:]]+(\"?)([A-Za-z0-9_]+)\1/CREATE TABLE IF NOT EXISTS ${DEVICE_SCHEMA}.\\1\\2\\1/gI;
    s/CREATE INDEX[[:space:]]+(\"?)([A-Za-z0-9_]+)\1/CREATE INDEX IF NOT EXISTS \\1\\2\\1/gI;
    s/([[:space:]]+)ON[[:space:]]+(\"?)([A-Za-z0-9_]+)\2/\\1ON ${DEVICE_SCHEMA}.\\2\\3\\2/gI;
  " > "$SCHEMA_SQL_PHASE2"
  
  psql -v ON_ERROR_STOP=1 -d "$PG_DB" -f "$SCHEMA_SQL_PHASE2" 2>&1 | tee -a "$LOGFILE"
fi

# Import data
echo "[*] Importing data"
TABLES="$(sqlite3 "$SQLITE_FILE" ".tables" | tr -s '[:space:]' '\n' | grep -v '^$')"

for TABLE in $TABLES; do
  echo "    [+] Importing: $TABLE"
  sqlite3 "$SQLITE_FILE" -header -csv "SELECT * FROM \"$TABLE\";" \
    | psql -v ON_ERROR_STOP=1 -d "$PG_DB" \
      -c "\copy ${DEVICE_SCHEMA}.\"$TABLE\" FROM STDIN WITH (FORMAT csv, HEADER true)" \
    2>&1 | tee -a "$LOGFILE"
done

echo "[*] Import complete!"
echo "    Verify: psql -d $PG_DB -c '\dt ${DEVICE_SCHEMA}.*'"
echo "    Log:    $LOGFILE"
