global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning
      receiver: 'warning-alerts'

receivers:
  - name: 'default'
    # Default receiver - can be configured with webhook, email, etc.

  - name: 'critical-alerts'
    # Critical alerts - configure for immediate notification
    # Example webhook:
    # webhook_configs:
    #   - url: 'http://your-webhook-url/critical'

  - name: 'warning-alerts'
    # Warning alerts - configure for standard notification
    # webhook_configs:
    #   - url: 'http://your-webhook-url/warning'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
